### ISSUE TITLE
Can't use meteor user in mosca authentication methods

### ISSUE THREAD

**Issue by iascchen** [mkarliner/meteor-mosca#4]
I created a mqtt mosca server as follow, but I can't use meteor collection in authentication() method, it will return Error: Can't wait without a fiber, here is my code :

```
var ascoltatore = {
    //using ascoltatore
    type: 'mongo',
    url: 'mongodb://localhost:3001/mqtt',
    pubsubCollection: 'ascoltatori',
    mongo: {}
};

var settings = {
    port: 1883,
    backend: ascoltatore
};

var server = new mosca.Server(settings);

var user = Meteor.users.find().fetch();  // this sentences works ok
console.log("user", user); 

// Accepts the connection if the username and password are valid
var authenticate = function (client, username, password, callback) {

    console.log("user", username, password.toString());

    var user2 = Meteor.users.find({
            _id: "fCishK3WBCpPWvctY"
        }).fetch();   // this sentences throw Error: Can't wait without a fiber
    console.log("user", user2);
};

// In this case the client authorized as alice can publish to /users/alice taking
// the username from the topic and verifing it is the same of the authorized user
var authorizePublish = function (client, topic, payload, callback) {
    var ok = client.user == topic.split('/')[2];
    // we can alter the message here
    if (ok)
        callback(null, payload);
    else
        callback(null, false);
};

// In this case the client authorized as alice can subscribe to /users/alice taking
// the username from the topic and verifing it is the same of the authorized user
var authorizeSubscribe = function (client, topic, callback) {
    var ok = client.user === topic.split('/')[2];
    callback(null, ok);
};

// fired when the mqtt server is ready
function setup() {
    server.authenticate = authenticate;
    server.authorizePublish = authorizePublish;
    server.authorizeSubscribe = authorizeSubscribe;

    console.log('mCotton mqtt server is up and running');
}

server.on('ready', setup);

server.on('clientConnected', function (client) {
    console.log('mqtt client connected', client.id);
});
```

**Comment by rjhllr** [comment]
+1

**Comment by mkarliner** [comment]
Sorry guys, I did actually miss this bug when it was originally posted.
That being said, I'm not sure how to get around this, as the error
pretty much sums up the issue.
I know it sounds barmy, but what about creating an HTTP authentication service in meteor which mosca can use? That might get around the async/fibre  issue.

Mike

**Comment by rjhllr** [comment]
Hey Mike,
I've tried just that. The problem is that I can't use Meteor's HTTP library inside of that callback as well (even though it's async). 

```
var authenticate = function(client, username, password, callback) {
  HTTP.call( 'METHOD', 'http://url.to/call', { "options": "to set" }, function( error, response ) {
    console.log(response)
  });
  callback(null, authorized);
}
```

Will throw just the same error. Perhaps one could try using NodeJS's core HTTP client, but I'm unsure on how to do just that.
I've also tried wrapping it in bindEnvironment which does not make things better nor worse.

**Comment by mkarliner** [comment]
Well, the other alternative is simply to create a node instance with Mosca as a standalone.

**Comment by rjhllr** [comment]
This is only partially relevant to this issue, but describes an _acceptable_ workaround.
I've gone with the original [mosca](https://github.com/mcollina/mosca/) and wrote a NodeJS implementation that uses Meteor's Mongo database. You can get it's URL using:

```
exec("meteor mongo -U", function (error, stdout, stderr) {
```

in NodeJS and checking the stdout for the mongodb URL scheme.
Mosca allows to use a pre-created Mongo client so I can reuse that in the authentication method to check the user/password against the database. It seems **cleaner** and potentially **faster** than using an HTTP API and provides most of the functionality I had hoped for in meteor-mosca, which is why I'm typing this up. 

Hope this can be of help to fellows facing the same problem.

**Comment by mkarliner** [comment]
Thanks very much for working this out.
Mike
